language: java
after_success:
  - mvn clean test jacoco:report coveralls:report
git:
  quiet: true
cache:
  directories:
    - $HOME/.m2
branches:
  only:
    - master
    - stable
notifications:
  email: false