language: java
addons:
  sonarcloud:
    organization: nighma
script:
- mvn clean test jacoco:report install sonar:sonar -Dsonar.projectKey=NiGhMa_be-checklist
after_success:
- mvn clean test jacoco:report coveralls:report
git:
  quiet: true
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
branches:
  only:
    - master
    - stable
notifications:
  email: false
